(function(){
var root="F:/modal-gui/series/04-joseon-exam",project=root+"/ae/04-joseon-exam-master.aep",output=root+"/ae/04-joseon-exam-master.avi",log=root+"/ae/04-joseon-exam-master.log";
var W=1920,H=1080,FPS=24,SHOT=5,ivory=[0.96,0.91,0.78],gold=[0.9,0.68,0.28],ink=[0.07,0.07,0.09];
var captions=[["조선에도","수험생이 있었어요"],["붓과 종이로","공부했어요"],["시험장에 모여","실력을 겨뤘어요"],["답안과 이름은","엄격하게 관리했어요"],["공부는 관직으로","가는 길이었어요"],["그들의 시험은","조선의 지식이 되었어요"]];
var clips=[root+"/clips/c1.mp4",root+"/clips/c2.mp4",root+"/clips/c3.mp4",root+"/clips/c4.mp4",root+"/clips/c5.mp4",root+"/clips/c6.mp4"];
var positions=[[1250,410],[130,760],[960,770],[150,760],[1200,410],[960,790]];
function note(s){var f=new File(log);f.open("a");f.writeln(new Date().toString()+" "+s);f.close();}
function addType(c,v,x,y,size,col,b,e,center){var l=c.layers.addText(v),sp=l.property("Source Text"),d=sp.value;d.font="BMJUA";d.fontSize=size;d.fillColor=col;d.applyFill=true;d.applyStroke=true;d.strokeColor=ink;d.strokeWidth=2;d.justification=center?ParagraphJustification.CENTER_JUSTIFY:ParagraphJustification.LEFT_JUSTIFY;sp.setValue(d);var t=l.property("ADBE Transform Group"),p=t.property("ADBE Position"),o=t.property("ADBE Opacity"),s=t.property("ADBE Scale");p.setValueAtTime(0,[x,y+55]);p.setValueAtTime(b,[x,y+55]);p.setValueAtTime(e,[x,y]);o.setValueAtTime(0,0);o.setValueAtTime(b,0);o.setValueAtTime(e,100);s.setValueAtTime(0,[70,70]);s.setValueAtTime(b,[70,70]);s.setValueAtTime(e,[108,108]);s.setValueAtTime(e+0.15,[100,100]);}
try{app.newProject();app.beginUndoGroup("Joseon exam kinetic master");var master=app.project.items.addComp("04 JOSEON EXAM / MASTER",W,H,1,30,FPS);
for(var i=0;i<6;i++){var f=new File(clips[i]);if(!f.exists)throw new Error("Missing "+f.fsName);var fi=app.project.importFile(new ImportOptions(f)),c=app.project.items.addComp("SHOT "+(i+1),W,H,1,SHOT,FPS),v=c.layers.add(fi),cover=Math.max(W/fi.width,H/fi.height)*100;v.property("ADBE Transform Group").property("ADBE Scale").setValue([cover,cover]);v.outPoint=SHOT;var p=positions[i],center=i===5;addType(c,captions[i][0],p[0],p[1],i===5?84:70,ivory,0.42,0.78,center);addType(c,captions[i][1],p[0],p[1]+105,i===5?78:76,gold,0.82,1.22,center);var sl=master.layers.add(c);sl.startTime=i*SHOT;sl.inPoint=i*SHOT;sl.outPoint=(i+1)*SHOT;}
var mf=new File(root+"/music-30s.wav"),mi=app.project.importFile(new ImportOptions(mf)),ml=master.layers.add(mi);ml.outPoint=30;var q=app.project.renderQueue.items.add(master);q.outputModule(1).file=new File(output);app.project.save(new File(project));app.endUndoGroup();note("SAVED "+project+" layers="+master.numLayers);app.quit();
}catch(e){note("ERROR "+e.toString()+" line="+e.line);try{app.endUndoGroup();}catch(ignore){}app.quit();}
})();
