(function(){
  var root="F:/modal-gui/series/03-kim-jeong-ho", project=root+"/ae/03-kim-jeong-ho-master.aep", output=root+"/ae/03-kim-jeong-ho-master.avi", log=root+"/ae/03-kim-jeong-ho-master.log";
  var W=1920,H=1080,FPS=24,SHOT=5,ivory=[0.96,0.91,0.78],gold=[0.90,0.68,0.28],ink=[0.07,0.07,0.09];
  var captions=[["김정호는","지도를 만들었어요"],["목판에 새겨","널리 보급했어요"],["산과 물길을","한눈에 담고"],["전국의 길과 고을을","정리했어요"],["지도는 지식이 되어","사람들에게 갔어요"],["대동여지도","길을 기록한 기술"]];
  var clips=[root+"/clips/c1.mp4",root+"/clips/c2.mp4",root+"/clips/c3.mp4",root+"/clips/c4.mp4",root+"/clips/c5.mp4",root+"/clips/c6.mp4"];
  var positions=[[1240,410],[1300,760],[140,180],[1250,180],[180,790],[960,800]];
  function note(s){var f=new File(log);f.open("a");f.writeln(new Date().toString()+" "+s);f.close();}
  function addType(comp,value,x,y,size,color,start,end,center){var l=comp.layers.addText(value),sp=l.property("Source Text"),d=sp.value;d.font="BMJUA";d.fontSize=size;d.fillColor=color;d.applyFill=true;d.applyStroke=true;d.strokeColor=ink;d.strokeWidth=2;d.justification=center?ParagraphJustification.CENTER_JUSTIFY:ParagraphJustification.LEFT_JUSTIFY;sp.setValue(d);var t=l.property("ADBE Transform Group"),p=t.property("ADBE Position"),o=t.property("ADBE Opacity"),s=t.property("ADBE Scale");p.setValueAtTime(0,[x,y+55]);p.setValueAtTime(start,[x,y+55]);p.setValueAtTime(end,[x,y]);o.setValueAtTime(0,0);o.setValueAtTime(start,0);o.setValueAtTime(end,100);s.setValueAtTime(0,[70,70]);s.setValueAtTime(start,[70,70]);s.setValueAtTime(end,[108,108]);s.setValueAtTime(end+0.15,[100,100]);}
  try{app.newProject();app.beginUndoGroup("Kim Jeong-ho kinetic master");var master=app.project.items.addComp("03 KIM JEONG HO / MASTER",W,H,1,30,FPS);
    for(var i=0;i<6;i++){var f=new File(clips[i]);if(!f.exists)throw new Error("Missing "+f.fsName);var fi=app.project.importFile(new ImportOptions(f)),c=app.project.items.addComp("SHOT "+(i+1),W,H,1,SHOT,FPS),v=c.layers.add(fi),cover=Math.max(W/fi.width,H/fi.height)*100;v.property("ADBE Transform Group").property("ADBE Scale").setValue([cover,cover]);v.outPoint=SHOT;var x=positions[i][0],y=positions[i][1],center=i>=4;addType(c,captions[i][0],x,y,70,ivory,0.42,0.78,center);addType(c,captions[i][1],x,y+105,i===5?84:76,gold,0.82,1.22,center);var sl=master.layers.add(c);sl.startTime=i*SHOT;sl.inPoint=i*SHOT;sl.outPoint=(i+1)*SHOT;}
    var mf=new File(root+"/music-30s.wav"),mi=app.project.importFile(new ImportOptions(mf)),ml=master.layers.add(mi);ml.outPoint=30;var q=app.project.renderQueue.items.add(master);q.outputModule(1).file=new File(output);app.project.save(new File(project));app.endUndoGroup();note("SAVED "+project+" layers="+master.numLayers);app.quit();
  }catch(e){note("ERROR "+e.toString()+" line="+e.line);try{app.endUndoGroup();}catch(ignore){}app.quit();}
})();
