(function(){
var dataRoot=$.getenv("MODAL_GUI_DATA_ROOT")||new File($.fileName).parent.parent.fsName+"/data",root=dataRoot+"/series/02-turtle-ship", project=root+"/ae/02-turtle-ship-master.aep", output=root+"/ae/02-turtle-ship-master.avi", log=root+"/ae/02-turtle-ship-master.log";
  var W=1920,H=1080,FPS=24,SHOT=5,ivory=[0.96,0.91,0.78],gold=[0.90,0.68,0.28],ink=[0.07,0.07,0.09];
  var captions=[["거북선은","이순신보다 먼저 있었을까?"],["나무와 철로 만든","조선의 전투선"],["등판을 덮은 구조가","적의 공격을 막았어요"],["바다에서 움직이는","과학기술"],["배와 항해술이","함께 발전했어요"],["거북선의 시작은","오래된 기술에서 왔어요"]];
  var clips=[root+"/clips/c1.mp4",root+"/clips/c2.mp4",root+"/clips/c3.mp4",root+"/clips/c4.mp4",root+"/clips/c5.mp4",root+"/clips/c6.mp4"];
  var positions=[[1300,420],[1350,760],[140,190],[140,760],[980,820],[960,790]];
  function note(s){var f=new File(log);f.open("a");f.writeln(new Date().toString()+" "+s);f.close();}
  function addType(comp,value,x,y,size,color,start,end,center){var l=comp.layers.addText(value),sp=l.property("Source Text"),d=sp.value;d.font="BMJUA";d.fontSize=size;d.fillColor=color;d.applyFill=true;d.applyStroke=true;d.strokeColor=ink;d.strokeWidth=2;d.justification=center?ParagraphJustification.CENTER_JUSTIFY:ParagraphJustification.LEFT_JUSTIFY;sp.setValue(d);var t=l.property("ADBE Transform Group"),p=t.property("ADBE Position"),o=t.property("ADBE Opacity"),s=t.property("ADBE Scale");p.setValueAtTime(0,[x,y+55]);p.setValueAtTime(start,[x,y+55]);p.setValueAtTime(end,[x,y]);o.setValueAtTime(0,0);o.setValueAtTime(start,0);o.setValueAtTime(end,100);s.setValueAtTime(0,[70,70]);s.setValueAtTime(start,[70,70]);s.setValueAtTime(end,[108,108]);s.setValueAtTime(end+0.15,[100,100]);}
  try{app.newProject();app.beginUndoGroup("Turtle ship kinetic master");var master=app.project.items.addComp("02 TURTLE SHIP / MASTER",W,H,1,30,FPS);
    for(var i=0;i<6;i++){var f=new File(clips[i]);if(!f.exists)throw new Error("Missing "+f.fsName);var fi=app.project.importFile(new ImportOptions(f)),c=app.project.items.addComp("SHOT "+(i+1),W,H,1,SHOT,FPS),v=c.layers.add(fi),cover=Math.max(W/fi.width,H/fi.height)*100;v.property("ADBE Transform Group").property("ADBE Scale").setValue([cover,cover]);v.outPoint=SHOT;var pos=positions[i],center=i>=4;addType(c,captions[i][0],pos[0],pos[1],i===5?86:70,ivory,0.42,0.78,center);addType(c,captions[i][1],pos[0],pos[1]+105,i===5?76:76,gold,0.82,1.22,center);var sl=master.layers.add(c);sl.startTime=i*SHOT;sl.inPoint=i*SHOT;sl.outPoint=(i+1)*SHOT;}
    var mf=new File(root+"/music-30s.wav"),mi=app.project.importFile(new ImportOptions(mf)),ml=master.layers.add(mi);ml.outPoint=30;var q=app.project.renderQueue.items.add(master);q.outputModule(1).file=new File(output);app.project.save(new File(project));app.endUndoGroup();note("SAVED "+project+" layers="+master.numLayers);app.quit();
  }catch(e){note("ERROR "+e.toString()+" line="+e.line);try{app.endUndoGroup();}catch(ignore){}app.quit();}
})();
